### ISSUE TITLE
Implement symbolic links in kernel

### ISSUE THREAD

**Issue by SirCmpwn** [KnightOS/KnightOS#146]
* [x] Update findFileEntry to support symlinks
* [x] Update genkfs to support symlinks
* [x] Implement createSymLink
* [x] Implement removeSymLink
* [x] Implement findEntry

`findEntry` is neccessary so that you can obtain a reference to an actual symlink node, rather than having it be followed by `findFileEntry`.

**Comment by SirCmpwn** [comment]
Note: removeSymLink has instead been implemented in deleteFile, which is being renamed to deleteNode.

**Comment by SirCmpwn** [comment]
Note: findFileEntry has been replaced by findNode, which supports symlinks.

**Comment by MaxLeiter** [comment]
https://github.com/KnightOS/kernel/commit/c07b3e21aa432e2867dd035afbf4c4116c6618b6 createSymLink was implemented by @unlimitedbacon
