### ISSUE TITLE
Add floating point/BCD support for assembly programs

### ISSUE THREAD

**Issue by SirCmpwn** [KnightOS/KnightOS#216]
We need calculators to be able to do math! We have (limited) floating point via libc, with all the errors that come with. We can do error corrections or we can do BCD, but somehow we need math support.

**Comment by ajcord** [comment]
Would you be opposed if I took a crack at this? I was thinking of starting with syscalls for the basic BCD routines, plus some conversions between BCD and integers. For simplicity, I would probably use a subset of the data structure that TI-OS uses for reals.

**Comment by SirCmpwn** [comment]
By all means, please do. Stop by the IRC channel if you have questions.
