### ISSUE TITLE
sed error in install-sdk script

### ISSUE THREAD

**Issue by Jnesselr** [KnightOS/KnightOS#230]
The Mac OS X (10.9.5) version of sed apparently doesn't have a '-r' option. This page says to replace the -r with -E, which didn't complain: http://www.flashesofpanic.com/panic/002596.php

**Comment by MaxLeiter** [comment]
Fixed by https://github.com/KnightOS/knightos.org/commit/125d0fe5af5cf6cd394fe2b0fe370fe750c52c7a#diff-87cf431bc227be1d2dbef7aa77cd8138
