### ISSUE TITLE
Implement interactive debugging on TKO

### ISSUE THREAD

**Issue by SirCmpwn** [KnightOS/KnightOS#241]
This should include at least a few features:
- Interface to core z80e debugger
- Breakpoints
- Memory and register examination
- Execution control (step, step over, step out)
- Port monitor

**Comment by unlimitedbacon** [comment]
I would love to have the ability to view a screen buffer in ram so you
could watch a program change it as it executes and not have to wait for it
to get swapped out to the LCD.

This should include at least a few features:

   - Interface to core z80e debugger
   - Breakpoints
   - Memory and register examination
   - Execution control (step, step over, step out)
   - Port monitor

—
Reply to this email directly or view it on GitHub
<https://github.com/KnightOS/KnightOS/issues/241>.

**Comment by SirCmpwn** [comment]
The screen isn't memory mapped.

**Comment by unlimitedbacon** [comment]
Right but we still keep screen buffers in memory. Essentially I want to be
able to tell the debugger "This here is a screen buffer. Render its
contents."

**Comment by SirCmpwn** [comment]
I see. That'd be nice but it's probably not a priority.
