### ISSUE TITLE
Kernel documentation viewer for TKO

### ISSUE THREAD

**Issue by SirCmpwn** [KnightOS/KnightOS#243]
The kernel docs are available as JSON here: http://www.knightos.org/documentation/reference/data.json

It would be super dooper cool if we could do something like hover over a pcall to get docs, or click it to open up the relevant page on [knightos.org](http://www.knightos.org/documentation/reference/).

**Comment by MaxLeiter** [comment]
https://github.com/KnightOS/try.knightos.org/pull/11
