### ISSUE TITLE
Visual interactive keypad for TKO

### ISSUE THREAD

**Issue by SirCmpwn** [KnightOS/KnightOS#247]
It'd be nice if you could see the entire keypad and click buttons.

**Comment by udara28** [comment]
SirCmpwn I like to try implementing this feature. I forked KnightOS/try.knightos.org repo but coudn't get the site to work. Is there additional things I must do to setup the enviorment

**Comment by SirCmpwn** [comment]
Yes. It's a jekyll site, so you'll want to look up the docs for that and get it working.

**Comment by udara28** [comment]
Can you have a look at http://try-knightos-org-udara28.c9.io/ I get the digit keys to work with the emulator.

**Comment by SirCmpwn** [comment]
Nicely done, @udara28. It seems to work correctly.

**Comment by s0r00t** [comment]
There's a graphical glitch for me on hover, using Firefox Dev Edition :
http://i.imgur.com/beO7euz.png

**Comment by udara28** [comment]
@s0r00t thanks for pointing out I was working with a chrome browser and didnt noticed. 
@SirCmpwn I take into account your comment on the screen size so I added an option to toggle screen which is accessible via settings.

**Comment by udara28** [comment]
I made a pull request on this enhancement please review and accept.

**Comment by udara28** [comment]
@SirCmpwn could you kindly have a look at the pull request regarding this issue https://github.com/KnightOS/try.knightos.org/pull/3 
I have temporarily hosted TKO at http://try-knightos-org-udara28.c9.io with the made changes.

**Comment by SirCmpwn** [comment]
Sorry for the wait. I will review this once I resolve the issue with GitHub about CORS support for the release API.

**Comment by udara28** [comment]
@SirCmpwn why this pull request was closed

**Comment by SirCmpwn** [comment]
GitHub never resolved the issue. I've deprecated TKO.
