### ISSUE TITLE
The CSE has errornous key detection

### ISSUE THREAD

**Issue by EphraimB** [KnightOS/KnightOS#252]
This is probably caused by some sort of hardware delay that was introduced in the new calc. To reproduce, press F3 at the castle and observe that the cursor moves right. Also possible: press 5 in Phoenix and move right.

**Comment by EphraimB** [comment]
This is wierd because before that Settings upgrade, that issue didn't exist.

**Comment by SirCmpwn** [comment]
The castle was also upgraded around the same time, changing the way it handles input. This issue has been present for a while, it was just made obvious by this change.

**Comment by EphraimB** [comment]
The last app is also highlighted by default when you turn on the calculator

**Comment by SirCmpwn** [comment]
This has been fixed.

**Comment by EphraimB** [comment]
Oh no! It goes down 1 row when you press Graph unless the last app in the Castle is highlighted.
