### ISSUE TITLE
Lock Screen with notifications and password

### ISSUE THREAD

**Issue by EphraimB** [KnightOS/KnightOS#255]

**Comment by EphraimB** [comment]
I'm working on it now

**Comment by SirCmpwn** [comment]
Note that this would be best as an app in community, rather than a core app.

**Comment by EphraimB** [comment]
What do you mean by an app in community?

**Comment by SirCmpwn** [comment]
The community repository.

https://packages.knightos.org/guidelines

**Comment by EphraimB** [comment]
Where in GitHub should I paste my code?

**Comment by SirCmpwn** [comment]
You should probably create a repository under your own GitHub account and publish your code there.

**Comment by EphraimB** [comment]
How do I publish my code after I made my own repository?

**Comment by s0r00t** [comment]
You should maybe come on the IRC for this kind of questions.

**Comment by SirCmpwn** [comment]
I encourage you to do more research about this subject on your own.
