### ISSUE TITLE
Show package contents and package.config

### ISSUE THREAD

**Issue by SirCmpwn** [KnightOS/KnightOS#273]
It'd be nice if we could view a package's contents and it's package.config file. The latter can be pulled out of a package with `kpack -i example.pkg`. The former is not supported by kpack without extracting the package.

**Comment by boos1993** [comment]
-Viewing package's contents is implemented with caching. Could use some visual enhancements https://github.com/KnightOS/packages.knightos.org/blob/master/styles/styles.scss#L22-L25

**Comment by SirCmpwn** [comment]
Thanks!
