### ISSUE TITLE
On the CSE, the castle border is ugly black.

### ISSUE THREAD

**Issue by EphraimB** [KnightOS/KnightOS#285]
I want the castle border changed to a castle wall

**Comment by SirCmpwn** [comment]
Can you mock up what you're hoping to see?

**Comment by EphraimB** [comment]
The color border on the to 84 plus CSE, I want the black color border replaced by a castle wall border.
![image](https://cloud.githubusercontent.com/assets/10489639/6731845/4238eb44-ce1e-11e4-98f3-fb2a9547cb7e.jpg)

**Comment by SirCmpwn** [comment]
At some point we'll let you customize the color of that, but we can't draw an image there for performance reasons. Also, at some point we'll have a color mode castle that uses the full screen anyway.
