### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by EphraimB** [KnightOS/KnightOS#292]
I feel like sound without plugging in headphones is possible if someone messes around with the IO a lot. Maybe it's possible for sound to come out of the IO port. I feel like KnightOS should have support for built-in sound. I'm sure it could become important to have it built-in to KnightOS.

**Comment by SirCmpwn** [comment]
I don't see a use-case for this being built-in, but anyone is welcome to write software that uses the I/O port for sound.
