### ISSUE TITLE
Calendar should still work without an RTC

### ISSUE THREAD

**Issue by SirCmpwn** [KnightOS/KnightOS#299]
You should still be able to browse the calendar without a RTC in your calculator (i.e. TI-73 and TI-83+). All of the date/time math works fine without one. It should just pick some date and show you that instead of the current date.

**Comment by SirCmpwn** [comment]
Paging @Willem3141

**Comment by Willem3141** [comment]
I'll do that this weekend.

**Comment by SirCmpwn** [comment]
Awesome, thanks.

**Comment by Willem3141** [comment]
Fixed by commit KnightOS/calendar@8ff3ad0.

**Comment by SirCmpwn** [comment]
Thanks!
