### ISSUE TITLE
Show icons in app list on castle

### ISSUE THREAD

**Issue by SirCmpwn** [KnightOS/KnightOS#303]
The application list should show the icon for each entry. I was thinking we'd put the icon in the upper right corner and change it depending on what you have selected.

**Comment by Jaspi10** [comment]
I'll try to do it like mentioned above.

**Comment by SirCmpwn** [comment]
Great! Let me know if you need any help.

**Comment by Ivoah** [comment]
I remember asking this before on IRC, but can't remember what you said: do you want a border around the icon?

**Comment by SirCmpwn** [comment]
Let's see it with and without and then decide.

**Comment by Ivoah** [comment]
Without borders: ![without borders](http://web.archive.org/web/20150610162008/http://a.pomf.se/dqzcfk.png)
With borders: ![with borders](http://web.archive.org/web/20150611220221/http://a.pomf.se/irhfdh.png)

**Comment by SirCmpwn** [comment]
Agreed.

**Comment by SirCmpwn** [comment]
You should show "All Programs" at the top, too (isn't that already there?)

**Comment by Ivoah** [comment]
That image was hand drawn in a pixel art program from a screenshot

**Comment by SirCmpwn** [comment]
Oh, alright.

**Comment by Ivoah** [comment]
SirCmpwn implemented this in this commit: KnightOS/castle@f188557b28ba66ab6cf482d34fadfb5e51c00b77
