### ISSUE TITLE
Signed comparisons do not work correctly with kcc/scas

### ISSUE THREAD

**Issue by SirCmpwn** [KnightOS/KnightOS#304]
Attempting to check if a `int8_t` is less than zero will always return false.

**Comment by pixelherodev** [comment]
This appears to have been fixed at some point.

```cpp
signed char getVar();

void main() {
	signed char c = getVar();
	if (c < 0) {
		while(1);
//		__asm__("jr $");
	}
}

```
I compiled that with `kcc a.c -S -o a.asm`.

I ran my z80 truncator on that file and got this:

```asm
_main_start::
_main:
	call	_getVar
	bit	7, l
	ret	Z
00102$:
	jp	00102$
	_main_end::
```
Functions returning one byte do so in register l, and an 8-bit signed value is negative if bit 7 is set.
If bit seven is not set - i.e., if it's zero - then the number is not less than zero.
