### ISSUE TITLE
z80e-sdl segfaults on cygwin64

### ISSUE THREAD

**Issue by pimathbrainiac** [KnightOS/KnightOS#307]
when running a make run on the assembly template project, a segfault is encountered on cygwin64 running on Windows 8.1

$ make run
z80e-sdl -d TI84pSE .knightos/debug.rom
.knightos/sdk.make:22: recipe for target 'run' failed
make: *** [run] Segmentation fault (core dumped)

**Comment by SirCmpwn** [comment]
z80e-sdl doesn't work on Cygwin (and shoudln't even come with install-sdk, that's weird).

**Comment by pimathbrainiac** [comment]
It doesn't, but I compiled it from the git repo. Thanks for the info.

**Comment by SirCmpwn** [comment]
Ah, cool. You can try this, though: https://github.com/matrefeytontias/z80e-sdl-win
