### ISSUE TITLE
Clicking 'Run' five times returns 'Cannot enlarge memory arrays'

### ISSUE THREAD

**Issue by MaxLeiter** [KnightOS/KnightOS#327]
Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
    
    Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.

The message is printed twice in the console

**Comment by SirCmpwn** [comment]
This is a known problem with TKO.
