### ISSUE TITLE
Help with installing pkg, can I use tilp to send programs through?

### ISSUE THREAD

**Issue by aurey2244** [KnightOS/KnightOS#328]
I'm just very confused about this subject, i really dont know how to add or do anything with this os, dont get me wrong this is really cool, and i finally got it sent through to my TI-84+CSE and replaced the regular os, to find out it works great expect for 2 apps that don't show because of lack of ram or something like that( any ideas on how to fix that?). So i was just wondering if its the same way somehow to send games and apps through using tilp? (BTW I'm using tilp for Ubuntu, took me forever just to figure out how to send apps to my calc do to compatiblity issues, had to change the extensions that had the letter c in them to the letter x( EX: doorsCSE.8ck --> doorsCSE.8xk)) and also what can i do exactly when i use the option to unlock my flash?

**Comment by SirCmpwn** [comment]
You can't install new things yet (not implemented), but you can recompile your OS with whatever you want pre-installed and send that over.

Unlocking your flash is an option for advanced users, do not play with it.
