### ISSUE TITLE
please forgive

### ISSUE THREAD

**Issue by aurey2244** [KnightOS/KnightOS#329]
Ik this may sound stupid but is there anyway in particular that i could reach u for anymore questions, ik im not supposd to post that stuff here but i just wanted some extra help

**Comment by SirCmpwn** [comment]
Chat on the IRC channel.

**Comment by SirCmpwn** [comment]
http://www.knightos.org/irc/

**Comment by aurey2244** [comment]
thanks man i really appreciate it
