### ISSUE TITLE
Some doubts about KnightOS

### ISSUE THREAD

**Issue by Maslor** [KnightOS/KnightOS#346]
I have the following doubts:
1- If I install KnightOS on my TI84+, does it support the functionalities of the standard TI OS (graphing and such)?
2- The standard OS on a TI84+ cannot read PDF files (correct me if I'm wrong). Would it be possible to read PDFs on KnightOS?

**Comment by javidhussain** [comment]
Dear sir,

                 I have read your mail but why have mailed me for?

       Waiting for your reply...

                                      Thanking you
