### ISSUE TITLE
Search placeholder text on packages.knightos.org shows package count that includes unsearchable packages

### ISSUE THREAD

**Issue by cacciatc** [KnightOS/KnightOS#347]
Since unapproved packages are not searchable the search count on the index page is misleading.

Relevant links:

* Where the search count comes from:
https://github.com/KnightOS/packages.knightos.org/blob/master/packages/blueprints/html.py#L30

* Where the search is performed:
https://github.com/KnightOS/packages.knightos.org/blob/master/packages/blueprints/html.py#L334

I just setup a dev env for packages.knightos.org (in fact having just uploaded 3 unapproved test packages made this small issue apparent). I will submit a PR fix if ye like.

**Comment by SirCmpwn** [comment]
PR would be great, thanks!

**Comment by cacciatc** [comment]
Is this issue up to me to close since the PR was accepted? I'm unsure of the proper etiquette here :)
