### ISSUE TITLE
KPACK: MacOS packing woes with rrootName

### ISSUE THREAD

**Issue by cacciatc** [KnightOS/KnightOS#355]
I mentioned in a kpack PR that packing does not consistently work for me on MacOS. Here are some sample errors I run into:

Duplicated path:

```
Error: couldn't open ./.knightos/pkgroot/var/packages./.knightos/pkgroot/var/packages/core/extra because
    No such file or directory
```

Superfluous spaces:

```
Error: couldn't open ./.knightos/pkgroot/var/packages   /core because
    No such file or directory
```

~~I believe I have isolated the issue to a call to opendir() at https://github.com/KnightOS/kpack/blob/master/src/packager.c#L393 Sometimes it works and sometimes it spits out something silly for the same inputs.~~

If I have time next week I might investigate using nftw instead which I believe is also available on Cygwin.

**Comment by MaxLeiter** [comment]
@cacciatc can you confirm this is still an issue? I can't repro on macOS 10.14

**Comment by cacciatc** [comment]
Hi @MaxLeiter, alas I no longer have access to that system so I cannot reproduce.

**Comment by pixelherodev** [comment]
Should this be closed as it can no longer be reproduced?

**Comment by pixelherodev** [comment]
Alright thanks, not an OS X user so didn't want to do it myself
