### ISSUE TITLE
ld hl errors

### ISSUE THREAD

**Issue by Snektron** [KnightOS/KnightOS#357]
Compiling `ld hl, 1` compiles into `ld hl, 0x2001`
Compiling `ld hl, ((1*(1+1)))` compiles into `ld hl, 0x2002` (rather than `ld hl, (0x2002)`)

**Comment by SirCmpwn** [comment]
[Cannot reproduce](https://asciinema.org/a/8n35i3tx45bd1d0mkat7be1nr)

**Comment by SirCmpwn** [comment]
Fixed in https://github.com/KnightOS/scas/commit/92e0440837a28dd7c15dd8f649165dbf31403404
