### ISSUE TITLE
wiki.knightos.org down

### ISSUE THREAD

**Issue by shadySource** [KnightOS/KnightOS#358]
I am getting ERR_CONNECTION_REFUSED.

**Comment by aycgit** [comment]
Packages.knightos.org also gives a bad gateway, seems like this project is semi-dead

**Comment by SirCmpwn** [comment]
Fixed packages.knightos.org. I'll get to wiki.knightos.org later, there's not really anything important on it.

**Comment by aviallon** [comment]
I personally found the wiki interesting for those who didn't know anything about this project.

**Comment by TechnologyClassroom** [comment]
The wiki is 404.

https://downforeveryoneorjustme.com/wiki.knightos.org

**Comment by Wqrld** [comment]
this is a really old issue from around 1 year ago and the last commit is from 3 years ago :) 
it doesn't seem to be maintained anymore

**Comment by TechnologyClassroom** [comment]
That is too bad.  It looks like an interesting project.

**Comment by MaxLeiter** [comment]
Contributions will still be accepted as pull requests. If you have questions feel free to join #knightos on freenode. The wiki was mostly useless.

**Comment by SirCmpwn** [comment]
Yeah, the wiki is deprecated. Rest of the project is still going, albiet very slowly.

**Comment by TechnologyClassroom** [comment]
Do you have access to editing the main site?  If so, remove all links to the wiki.

**Comment by SirCmpwn** [comment]
I can't really be bothered tbh. The code's here if you want to send a PR: https://github.com/KnightOS/knightos.org

**Comment by TechnologyClassroom** [comment]
Will do!
