### ISSUE TITLE
z80e macOS compile error

### ISSUE THREAD

**Issue by ajcord** [KnightOS/KnightOS#359]
When I run the SDK installer, I get the following output on macOS 10.12.5:
```
.../z80e/libz80e/src/debugger/commands/link.c:101:33: error: 
      use of undeclared identifier 'SOCK_NONBLOCK'
                socket(AF_UNIX, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0);
                                              ^
.../z80e/libz80e/src/debugger/commands/link.c:101:49: error: 
      use of undeclared identifier 'SOCK_CLOEXEC'
                socket(AF_UNIX, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0);
                                                              ^
```

Looks like SOCK_NONBLOCK and SOCK_CLOEXEC are Linux-specific. I tried removing those flags and adding the following line:
```C
fcntl(state->asic->link->listenfd.fd, F_SETFD, FD_CLOEXEC);
```
That got it to compile, but when I try running the default hello world ROM, z80e hangs with an empty screen. I think my fixes should be equivalent because line 102 already sets the nonblocking flag, and the line I added sets the close-on-exec flag. Any ideas?

**Comment by SirCmpwn** [comment]
Try pressing F12 - z80e doesn't automatically turn the calculator on.

**Comment by ajcord** [comment]
Thanks for the quick reply! F12 doesn't have any effect.

**Comment by SirCmpwn** [comment]
Are you sure you pressed F12 and not some macOS specific key? I know the F keys on OSX are weird. You could also try changing the key used for ON here:

https://github.com/KnightOS/z80e/blob/master/frontends/sdl/main.c#L370

I suspect that the link fd issue is unrelated.

**Comment by ajcord** [comment]
Remapping it to space doesn't seem to help either. It always just has a spinning beach ball cursor as if it's hanging.

**Comment by SirCmpwn** [comment]
Beach ball cursor is the ticket, then. What is this "default hello world ROM" you speak of? How are you starting z80e with it? I would also grab gdb and see if you can find out where it's hanging.

**Comment by Ivoah** [comment]
I think you need to type `run` (or similar) on the command line, and then try to turn it on.

**Comment by SirCmpwn** [comment]
Only if you use `--debug`

**Comment by ajcord** [comment]
@SirCmpwn I created a new z80 project with:
```
knightos init helloworld_asm
make
make run
```
lldb's output isn't very friendly since debug symbols are turned off. How would I turn those on in the makefile?

**Comment by SirCmpwn** [comment]
Use `-DCMAKE_BUILD_TYPE=Debug` when you run cmake.

**Comment by ajcord** [comment]
Wait! @Ivoah was right. Running with --debug worked. Wonder why it didn't hang?

@SirCmpwn Compiling with the debug flag you mentioned didn't generate symbols for most of the project, unfortunately. Only worked for cpu.c.

**Comment by SirCmpwn** [comment]
You'll have to do a `make clean` first. And if `--debug` works, how about just using that?

**Comment by ajcord** [comment]
Sure. Should I submit a PR with my more platform agnostic fcntl version?

**Comment by SirCmpwn** [comment]
Yes please.

**Comment by ajcord** [comment]
https://github.com/KnightOS/z80e/pull/44
