### ISSUE TITLE
New SDK is buggy

### ISSUE THREAD

**Issue by pixelherodev** [KnightOS/KnightOS#361]
I installed the SDK. I didn't use the install script, instead manually cloning, running cmake, compiling and installing. After a successful installation of the SDK as indicated by `knightos init hello_world --template=c` working without a problem. For some reason, the C library was missing. After manually running `knightos install extra/libc` and trying `make` again, there was a new problem: the C headers were missing. I ran `knightos install-base` and it proceeded to build and run properly.

Another problem: I cloned git://github.com/knightos/knightos.git, ran `knightos --init && make && make run` and got a message somewhere along the lines of "library failed to load - kernel error code 3." I ran `knightos install-base`, and, again, it worked.

**Comment by MaxLeiter** [comment]
@aviallon: how did you install the SDK/other programs like scas? Did you use git or distro packages?

**Comment by pixelherodev** [comment]
Current status: template for C works fine out of the box, building from this repo needs testing

**Comment by pixelherodev** [comment]
This repo's issue wasn't actually the SDK - configlib is a dependency which was missing from package.config.
