### ISSUE TITLE
SDK: 'make run' error loading shared libraries libscas.so

### ISSUE THREAD

**Issue by thefkats** [KnightOS/KnightOS#363]
Installed all sdk requirements on Ubuntu, manually added templates to: 
`/usr/local/lib/python3.5/dist-packages/knightos-2.0.3_5_ge4a38cc-py3.5.egg/knightos/`
make command was successful, however 'make run' gave the error:
`z80e-sdl -d TI84pSE .knightos/debug.rom
z80e-sdl: error while loading shared libraries: libscas.so: cannot open shared object file: No such file or directory
.knightos/sdk.make:22: recipe for target 'run' failed
make: *** [run] error 127`

Fixed by updating LD_LOAD_PATH
`sudo ldconfig`

**Comment by SirCmpwn** [comment]
Why closed?
