### ISSUE TITLE
packages.knightos.org and wiki.knightos.org down

### ISSUE THREAD

**Issue by aviallon** [KnightOS/KnightOS#364]
502 Bad Gateway for packages.knightos.org
and no server found for wiki.knightos.org (!)
What happened ? :(

**Comment by SirCmpwn** [comment]
Thanks for the head's up. packages.knightos.org is back up. The wiki has been down for a long time and will continue to stay that way; it was never of much value.

**Comment by aviallon** [comment]
Why ? :'(
