### ISSUE TITLE
Can't use download nor build KnightOS. Desperate

### ISSUE THREAD

**Issue by aviallon** [KnightOS/KnightOS#366]
builds.knightos.org is down, and I can't use knightos init : 
this is what I get : `FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/knightos-2.0.3_5_ge4a38cc-py3.6.egg/knightos/commands/../templates/assembly/assembly.yaml'
`
Can you fix the website or help me fix the build (error happens on a clean install of Ubuntu 17.10).

**Comment by SpaceboyRoss01** [comment]
I got the same error, I fixed it by copying the knightos directory from the sdk source to `/usr/local/lib/python3.6/dist-packages/knightos-2.0.3_5_ge4a38cc-py3.6.egg`

**Comment by pixelherodev** [comment]
@SpaceboyRoss01 @aviallon How did you install the SDK? A fresh install via `sudo ./setup.py install` works fine for me, all the files are copied properly. Do you still have the problem?

**Comment by aviallon** [comment]
Yeah works fine now. But it didn't work for some time.

Le ven. 19 oct. 2018 à 01:42, pixelherodev <notifications@github.com> a
écrit :
