### ISSUE TITLE
Add test suite to scas

### ISSUE THREAD

**Issue by pixelherodev** [KnightOS/KnightOS#375]

**Comment by ddevault** [comment]
scas != kcc

**Comment by pixelherodev** [comment]
I plan on just writing a bunch of simple asm files (possibly including some generated by KCC), and making sure they can be built properly / validating the hash of the output.

**Comment by pixelherodev** [comment]
Now that scas can build the kernel, this isn't really an issue. There's no point in directing effort here when it can be better spent fixing actual issues.
