### ISSUE TITLE
scas segfaults if options missing argument: -i, -I, -D

### ISSUE THREAD

**Issue by nmosier** [KnightOS/KnightOS#380]
(using macOS Mojave)

scas -i
Segmentation fault: 11

Backtrace:
thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
frame #0: 0x00007fff6e211712 libsystem_platform.dylib'_platform_strlen + 18
frame #1: 0x0000000100016389 scas'validate_scas_runtime at main.c:66
frame #2: 0x0000000100016efe scas'main(argc=2, argv=0x00007ffeefbff8c8) at main.c:202
frame #3: 0x00007fff6e029ed9 libdyld.dylib'start + 1
frame #4: 0x00007fff6e029ed9 libdyld.dylib'start + 1

The bug arises in parse_arguments() at main.c:81 -- the code doesn't check if the option actually has an argument.

I'd be happy to fix this bug myself and then create a pull request. Just thought I should still report the bug, however.

I'm also wondering, is there a reason why parse_arguments() doesn't use getopt(3)?

**Comment by pixelherodev** [comment]
Confirmed, thanks.

I don't think there's a pressing reason to use getopt. Parsing as is is easier to understand at a simple glance.

Do you plan on fixing this, or would you rather I handle it?

**Comment by pixelherodev** [comment]
Glad to have you on board!

It's been my experience that while scas (along with many of the other KnightOS components) can be hard to get familiar with at first, the source is actually pretty straightforward once you play around with it a bit (even if there are parts that need improvement here or there).

If you're serious about contributing, you might want to drop by the #knightos channel on FreeNode's IRC network. The old mailing list is down, but I've set up a new one [here](https://lists.sr.ht/~pixelherodev/knightos).

**Comment by nmosier** [comment]
I submitted a pull request with the bug fixes.

I just subscribed to the mailing list and will check out the #knightos channel as soon as I can get my nickname registration to work...

**Comment by pixelherodev** [comment]
PR merged.
