### ISSUE TITLE
Kimg fails to build on cygwin when running sdk installer, I think because it can't find the header in the path.

### ISSUE THREAD

**Issue by chexo3** [KnightOS/KnightOS#383]
```
$ ./install-sdk
Cygwin users - make sure you're running cygwin as administrator!
Downloading genkfs...
Compiling genkfs...
Installing genkfs...
Downloading mktiupgrade...
Compiling mktiupgrade...
Installing mktiupgrade...
Downloading kpack...
Compiling kpack...
Installing kpack...
Downloading kimg...
Compiling kimg...
Scanning dependencies of target man [ 33%] Generating kimg.1 a2x: WARNING: --destination-dir option is only applicable to HTML based outputs [ 33%] Built target man Scanning dependencies of target kimg [ 66%] Building C object CMakeFiles/kimg.dir/src/main.c.o /tmp/SDK.ZBxo3N/kimg/src/main.c:7:10: fatal error: MagickWand/MagickWand.h: No such file or directory #include <MagickWand/MagickWand.h> ^~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. make[2]: cmake_install.cmake CMakeCache.txt CMakeFiles CMakeLists.txt kimg.1 kimg.1.txt LICENSE Makefile README.md src [CMakeFiles/kimg.dir/build.make:63: CMakeFiles/kimg.dir/src/main.c.o] Error 1 make[1]: cmake_install.cmake CMakeCache.txt CMakeFiles CMakeLists.txt kimg.1 kimg.1.txt LICENSE Makefile README.md src [CMakeFiles/Makefile2:110: CMakeFiles/kimg.dir/all] Error 2 make: cmake_install.cmake CMakeCache.txt CMakeFiles CMakeLists.txt kimg.1 kimg.1.txt LICENSE Makefile README.md src [Makefile:130: all] Error 2
```

**Comment by MaxLeiter** [comment]
Try updating your imagemagick

**Comment by chexo3** [comment]
I switched to ubuntu subsystem for windows

i guess I'll try cygwin again

**Comment by chexo3** [comment]
also please update some of the listed dependencies for the sdk, I think some of them list older versions than are required

**Comment by MaxLeiter** [comment]
pull requests are welcome

**Comment by earboxer** [comment]
For posterity, before  https://github.com/KnightOS/kimg/commit/b0b42323cb1b92df2dc30b52391c261eef1eb232, we were supporting imagemagick version 6 (I'm able to compile it in Ubuntu 18.04 with the commit before this one (`git checkout b0b4232~1`)). Now, imagemagick 7 is required.

For searchability, here's the error I get when trying to compile the latest kimg in ubuntu 18.04.
```
kimg/src/main.c:7:10: fatal error: MagickWand/MagickWand.h: No such file or directory
 #include <MagickWand/MagickWand.h>
```

It looks like neither [debian](https://packages.debian.org/search?keywords=imagemagick&searchon=names&suite=stable&section=all), nor [ubuntu](https://packages.ubuntu.com/search?keywords=imagemagick&searchon=names&suite=eoan&section=all) is packaging imagemagick 7 yet (the imagemagick team is supporting [version 6](https://legacy.imagemagick.org) until 2026, and these distributions, preferring stability, are less likely to make the jump before then).

For us, this means the docker image will not be able to be rebuilt (the `install-sdk` script will fail) until we switch it to a distribution that has imagemagick 7, or update it to download and compile imagemagick 7.

**Comment by earboxer** [comment]
Alternatively, we could make install-sdk check your version of imagemagick, then decide to use kimg `0.2.1` vs `0.2.0`... (this would probably be the easiest way to help the most people, and assuming kimg won't have major development over the next 6 years, it wouldn't add to the maintenance cost).

**Comment by pixelherodev** [comment]
Or, we could make it compatible with both versions, and mark six as deprecated, eventually removing it when seven becomes ubiquitious, which I think is the best option. CMake can detect the version and automatically define the version, and kimg can be built to support whatever is available.
