### ISSUE TITLE
www.knightos.org not secure

### ISSUE THREAD

**Issue by salkin-mada** [KnightOS/KnightOS#384]
Your connection is not private
Attackers might be trying to steal your information from www.knightos.org (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID

Using brave browser, insisting on https.

**Comment by ddevault** [comment]
We don't use www. Go to https://knightos.org.

**Comment by salkin-mada** [comment]
> We don't use www. 
and I would not expect you to :+1: glad you dont.
i pressed a link and ended up with https://www.knightos.org/
would recommend you redirect away from www. but you for sure already know this.
just wanted to tell you that i experienced not being redirected to safety after pressing the knightOS homepage link (linted as https://www.knightos.org/) found at https://github.com/KnightOS
best
