### ISSUE TITLE
Clean up warnings in SDK packages

### ISSUE THREAD

**Issue by pixelherodev** [KnightOS/KnightOS#387]
Some packages, such as scas, emit a number of warnings during compilation. These should be fixed ~~so that -Werror can be enabled in development builds.~~ as many of them indicate bugs.

After the discussion that led to #402, -Werror shouldn't be enabled by default *ever*.

**Comment by MaxLeiter** [comment]
https://github.com/KnightOS/genkfs/pull/6

**Comment by pixelherodev** [comment]
That was a mistake: GCC disables `-Wformat-security` when `-Wall` is specified, so I didn't see the error.

Some packages currently don't have `-Werror` in their flags, because they *did* emit warnings during testing.

**Comment by pixelherodev** [comment]
Most of the serious ones have been addressed.
