### ISSUE TITLE
KnightOS for TI-Nspire series?

### ISSUE THREAD

**Issue by topikettunen** [KnightOS/KnightOS#394]
Hi!

I just recently stumbled upon this project and it seems very cool. Quickly I started thinking has there been any efforts in doing something similar for the successor TI-Nspire series by you or someone else? Or is it even possible?

I tried to Google something related to this, but with no luck.

**Comment by pixelherodev** [comment]
Unfortunately, KnightOS itself will never be able to support the Nspire. ` It uses a proprietary SoC of the ARM9 variant for its CPU.`

**Comment by pixelherodev** [comment]
I don't know of any similar projects for the Nspire. It could probably be done, but it would be a long-term project (measured in years) and would require a ton of effort.

**Comment by MaxLeiter** [comment]
Also, afaik, we don’t have Nspire boot keys so no custom OS
