### ISSUE TITLE
KCC can't understand variable declarations if another statement occured before

### ISSUE THREAD

**Issue by aviallon** [KnightOS/KnightOS#395]
For instance, this : 
```c
...
void main() {
    SCREEN* screen;
    get_lcd_lock();
    unsigned short i = 0;
    ...
}
```
fails to build with : `main.c:17: syntax error: token -> 'unsigned' ; column 12`
whereas : 
```c
...
void main() {
    SCREEN* screen;
    unsigned short i = 0;
    get_lcd_lock();
    ...
}
```
builds fine.

**Comment by MaxLeiter** [comment]
Not a bug, KCC supports [C89](https://stackoverflow.com/a/288479). You may have luck with the `--std-c99` flag. I think upstream supports it, not sure we do

**Comment by aviallon** [comment]
@MaxLeiter `--std-c99` is activated by default. However, the way Makefile are generated makes it obscure to me on how I am supposed to add any parameter to `kcc`

**Comment by pixelherodev** [comment]
I believe CFLAGS is respected. @aviallon
