### ISSUE TITLE
Issue with compiling KnightOS/patchrom

### ISSUE THREAD

**Issue by sorucoder** [KnightOS/KnightOS#406]
There is an error with all `fprintf(stderr, errorMessage);` calls at `main.c` in lines [53](https://github.com/KnightOS/patchrom/blob/ead9b594aeaf42586f52108289c81b0437b5629d/main.c#L53), [59](https://github.com/KnightOS/patchrom/blob/ead9b594aeaf42586f52108289c81b0437b5629d/main.c#L59), and [75](https://github.com/KnightOS/patchrom/blob/ead9b594aeaf42586f52108289c81b0437b5629d/main.c#L75). The particular error is that it seems to require a string literal for formatting, so I modified my personal copy to use `fprintf(stderr, "%s", errorMessage);` and it worked. I have also written this at the IRC as I was unsure of which place this would be most appropriate.

**Comment by sorucoder** [comment]
Fixed issue with this [pull request](https://github.com/KnightOS/patchrom/pull/4).

**Comment by pixelherodev** [comment]
@sorucoder Should be good now, reopen this issue if you still have issues.

**Comment by MaxLeiter** [comment]
@pixelherodev only maintainers can re-open issues, I think.  @sorucoder feel free to comment here or hop in IRC
