### ISSUE TITLE
install doesnt work

### ISSUE THREAD

**Issue by HacksAndSlash** [KnightOS/KnightOS#411]
Im using a TI-84 plus and KnightOS doesnt seem to be booting properly as its screen is corrupted on startup

**Comment by aviallon** [comment]
Hello, thanks for being interested in the project !
Which image did you install ? How did you do it ?
We'll try to help :)

**Comment by HacksAndSlash** [comment]
from the "Download Latest Version" then I transfered it using TILP on  xubuntu 20.04

**Comment by HacksAndSlash** [comment]
oh i forgot to mention my calc uses the newer hardware

**Comment by NonstickAtom785** [comment]
Hey HacksAndSlash. I had your same issue. I can't seem to use the one from the download page either. I was however able to compile it manually and use mktiupgrade to convert the ROM into an 8xu. :) Hope this helps! Also I don't know if it's legal to share KOS upgrade files but if it is then I would be more than happy to send you the upgrade file.

**Comment by pixelherodev** [comment]
It's perfectly legal.

I'll look into this soon.

**Comment by pixelherodev** [comment]
Okay, so: the build on KnightOS.org is broken right now? I can see about
manually upgrading it and checking what happened. keeping this open for
now.

**Comment by NonstickAtom785** [comment]
Oh okay. Also I know that the most recent build without modification has a bug with the power menu in Wabbit emu. Don't know if it is still like that on the actual calc. Also it "crashes", turns off a couple of times while navigating. I'll see if I can replicate because I noticed this about 4 days ago.

**Comment by pixelherodev** [comment]
If you can replicate, I can investigate :)

**Comment by HacksAndSlash** [comment]
@NonstickAtom785 Can You Send Me The 8xu?

**Comment by HacksAndSlash** [comment]
Can You Send Me The 8xu?

**Comment by NonstickAtom785** [comment]
> 
> 
> Can You Send Me The 8xu?

Yes. I'm reinstalling the sdk now. I'll update the comment when it's compiled.

**Comment by pixelherodev** [comment]
The "download latest" button is wrong and bad and I dunno how it got that way. Removing it shortly.
