### ISSUE TITLE
z80e doesn't build anymore because of scas

### ISSUE THREAD

**Issue by aviallon** [KnightOS/KnightOS#414]
It look likes scas cmake find hook doesn't exist anymore? Or at least it is not properly installed.
This causes a build failure for z80e which needs it.

**Comment by pixelherodev** [comment]
Thought this was already fixed... poke me in a few hours on irc.

**Comment by aviallon** [comment]
Bug exists even when building with curl `https://knightos.org/install-sdk | bash`

**Comment by pixelherodev** [comment]
Ah. That is a bug with install sdk, i believe.

**Comment by pixelherodev** [comment]
Screw it, using this as an excuse to write some makefiles, too.

**Comment by pixelherodev** [comment]
Not fudging with the build system at present.

I'd forgotten to add -DSCAS_LIBRARY=ON to install-sdk after making the library build optional previously. This is fixed now.
