### ISSUE TITLE
packages.knightos.org not accessible

### ISSUE THREAD

**Issue by ajokela** [KnightOS/KnightOS#418]
packages.knightos.org appears to be unresponsive; is it down indefinitely?

**Comment by BryceVandegrift** [comment]
Yes. The entire KnightOS SDK is currently being reworked so it won't depend on packages.knightos.org.

**Comment by MaxLeiter** [comment]
@ajokela if you'd like to follow the current progress I recommend joining #knightos on the Libera.Chat IRC network.
